version: "3.8"

services:
  php:
    build:
      context: ./.build/php
    volumes:
      - ./backend:/var/www/app
    environment:
      - DB_USER=test_user
      - DB_PASSWORD=test_pass
      - DB_NAME=test_db
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./backend:/var/www/app
      - ./.build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

volumes:
  db_data: