version: "3.8"

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php